[build]
  base = "example"
  publish = "dist"
  command = "pnpm install && pnpm build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--version"  # Skip npm install
  PNPM_FLAGS = "--no-frozen-lockfile" 